name: Auto-Enforce Project Structure

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  validate-structure:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Validate project structure
      run: |
        echo "🔍 Validating project structure..."
        
        # Check for backend logic in project root
        if find . -name "*.ts" -o -name "*.js" | grep -q "ai-systems\|core-systems\|advanced-features"; then
          echo "❌ ERROR: Backend logic found in project root!"
          exit 1
        fi
        
        # Check for root intelligence files
        if [ -f "README.md" ] && grep -q "RepoClone Intelligence" README.md; then
          echo "❌ ERROR: Root intelligence files found in project!"
          exit 1
        fi
        
        # Check for backend connector
        if [ ! -f "backend-connector.ts" ]; then
          echo "❌ ERROR: Missing backend-connector.ts!"
          exit 1
        fi
        
        # Check project schema
        if [ ! -f "PROJECT_SCHEMA.md" ]; then
          echo "❌ ERROR: Missing PROJECT_SCHEMA.md!"
          exit 1
        fi
        
        # Check project structure rules
        if [ ! -f "PROJECT_STRUCTURE_RULES.md" ]; then
          echo "❌ ERROR: Missing PROJECT_STRUCTURE_RULES.md!"
          exit 1
        fi
        
        echo "✅ Project structure validation passed!"
        
    - name: Validate template completeness
      run: |
        echo "🔍 Validating template completeness..."
        
        # Required directories
        required_dirs=("components" "pages" "templates" "assets" "config" "data-stores" "learning-data" "workflows")
        
        for dir in "${required_dirs[@]}"; do
          if [ ! -d "$dir" ]; then
            echo "⚠️  WARNING: Missing directory: $dir"
          else
            echo "✅ Found directory: $dir"
          fi
        done
        
        # Required files
        required_files=("package.json" "README.md" "backend-connector.ts" "PROJECT_SCHEMA.md" "PROJECT_STRUCTURE_RULES.md")
        
        for file in "${required_files[@]}"; do
          if [ ! -f "$file" ]; then
            echo "❌ ERROR: Missing required file: $file"
            exit 1
          else
            echo "✅ Found file: $file"
          fi
        done
        
        # Check backend logic references
        if grep -q "from '../backend-logic/" backend-connector.ts; then
          echo "✅ Backend logic properly referenced"
        else
          echo "❌ ERROR: Backend logic not properly referenced!"
          exit 1
        fi
        
        echo "✅ Template validation passed!"
        
    - name: Run project hooks
      run: |
        echo "🔍 Running project hooks..."
        
        if [ -f ".hooks/pre-commit" ]; then
          chmod +x .hooks/pre-commit
          .hooks/pre-commit
        fi
        
        if [ -f ".hooks/post-commit" ]; then
          chmod +x .hooks/post-commit
          .hooks/post-commit
        fi
        
        echo "✅ Project hooks passed!" 